### ISSUE TITLE
local build crashes at new world creation screen

### ISSUE THREAD

**Issue by dynamiteOpanty** [Zuiron/Photosynthesis#246]
so I was trying to build to test the mod by myself at eafadd99f5e61283ebd2412c8baf3a9fdb686cda , but couldn't it work
./gradlew runClient
game boots normally but it crashes on new world creating screen

builds that are distributed at modrinth works fine

```
[21:24:29] [Render thread/ERROR] (Minecraft) Registry loading errors:
 Errors in registry minecraft:root:
 Errors in element minecraft:worldgen/placed_feature:
java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/placed_feature]: [photosynthesis:cherrytree_checked]
        at net.minecraft.registry.SimpleRegistry.freeze(SimpleRegistry.java:360)
        at net.minecraft.registry.RegistryLoader.method_45128(RegistryLoader.java:103)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.registry.RegistryLoader.load(RegistryLoader.java:100)
        at net.minecraft.server.SaveLoading.loadDynamicRegistryManager(SaveLoading.java:67)
        at net.minecraft.server.SaveLoading.withRegistriesLoaded(SaveLoading.java:71)
        at net.minecraft.server.SaveLoading.load(SaveLoading.java:34)
        at net.minecraft.client.gui.screen.world.CreateWorldScreen.create(CreateWorldScreen.java:333)
        at net.minecraft.client.gui.screen.world.SelectWorldScreen.method_19944(SelectWorldScreen.java:60)
        at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:94)
        at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:56)
        at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:189)
        at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38)
        at net.minecraft.client.Mouse.method_1611(Mouse.java:98)
        at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409)
        at net.minecraft.client.Mouse.onMouseButton(Mouse.java:98)
        at net.minecraft.client.Mouse.method_22686(Mouse.java:169)
        at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
        at net.minecraft.client.Mouse.method_22684(Mouse.java:169)
        at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
        at org.lwjgl.system.JNI.invokeV(Native Method)
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
        at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
        at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
        at net.minecraft.client.util.Window.swapBuffers(Window.java:288)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1241)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
        at net.minecraft.client.main.Main.main(Main.java:250)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

[21:24:29] [Render thread/ERROR] (Minecraft) Reported exception thrown!
 net.minecraft.util.crash.CrashException: mouseClicked event handler
        at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.Mouse.onMouseButton(Mouse.java:98) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.Mouse.method_22686(Mouse.java:169) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.Mouse.method_22684(Mouse.java:169) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
        at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:build 7]
        at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.util.Window.swapBuffers(Window.java:288) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1241) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]

Caused by: java.lang.IllegalStateException: Failed to load registries due to above errors
        at net.minecraft.registry.RegistryLoader.load(RegistryLoader.java:111) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.server.SaveLoading.loadDynamicRegistryManager(SaveLoading.java:67) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.server.SaveLoading.withRegistriesLoaded(SaveLoading.java:71) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.server.SaveLoading.load(SaveLoading.java:34) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.screen.world.CreateWorldScreen.create(CreateWorldScreen.java:333) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.screen.world.SelectWorldScreen.method_19944(SelectWorldScreen.java:60) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:94) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:56) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:189) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.Mouse.method_1611(Mouse.java:98) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409) ~[minecraft-merged-3b359ff646-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
        ... 17 more
```

**Comment by Zuiron** [comment]
no idea. builds and runs fine for me 🤷 maybe you forgot to run datagen ?

**Comment by dynamiteOpanty** [comment]
that fixed, my fault
